name: EPG update

on:
  schedule:
    - cron: '0 0 * * *' # Daily schedule
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
           node-version: 18
      
    - name: npm grab epg
      run: |
          npm install
          npm run grab -- --site=tvguide.myjcom.jp --output=guide.xml

    - name: curl -L -o live.xml "https://assets.livednow.com/epg.xml"
      run: |
        wget --user-agent="Mozilla/5.0" "https://assets.livednow.com/epg.xml" -O live.xml
        python epgmerge.py
          
    - name: Commit changes
      run: |
        git config --local user.email "your-email@example.com"
        git config --local user.name "Your Name"
        git add -f guide.xml epg.xml
        git commit -m "Update xml"
        git push
